### PR TITLE
Refactoring for easier palette definition

### PR DESCRIPTION
**Pull request by dhruvasagar**
I have refactored the definitions in an attempt to create a more scalable palette definition style.
A bunch of these color names are placeholders and would most likely need changing and relooking, some of them might need removing altogether.

Lets use this PR to discuss and take this further towards a much better colorscheme definition for vim.

### CODE REVIEW

**Comment by dhruvasagar** [comment]
Any thoughts ? I am sure there are things to improve and changes to make, especially to the pallete. Let me know what you think.

**Comment by jpo** [comment]
I think this is a good start. I've been comparing this approach to the [Solarized theme](https://github.com/altercation/vim-colors-solarized/blob/master/colors/solarized.vim). I'm not a vim expert by any means. But judging by the way you've set this up, is the goal to extract the palette functionality into it's own plugin?

**Comment by dhruvasagar** [comment]
@jpo That's not necessarily the goal, though it can be done that way. In general I'd like to limit `dependencies` to bare minimum so I wouldn't want that to be something to worry about at the moment.

My idea was more to easily be able to review the palette (especially by designers) to remove redundancy or identify highlight groups that should look more different from each other than they currently do.

**Comment by jpo** [comment]
I went ahead and merged this, but I noticed a couple of colors that were incorrect. For instance, the Identifier is marked as yellow when it should be darkorange_1. Error looks incorrect as well.

**Comment by dhruvasagar** [comment]
@jpo yeah I wanted it reviewed first, you can go ahead and revert and reopen this.

**Pull request merged**
